[parquet_to_minio.destination.filesystem]
bucket_url = ""

[parquet_to_minio.destination.credentials]
aws_access_key_id=""
aws_secret_access_key=""
endpoint_url = ""

[minio_to_azure.sources.filesystem.credentials]
aws_access_key_id=""
aws_secret_access_key=""
endpoint_url = ""

[minio_to_azure.destination.filesystem]
bucket_url = ""

[minio_to_azure.destination.filesystem.credentials]
azure_storage_account_name  = ""
azure_storage_account_key = ""

[minio_to_clickhouse.sources.filesystem.credentials]
aws_access_key_id=""
aws_secret_access_key=""
endpoint_url = ""

[minio_to_clickhouse.destination.clickhouse.credentials]
database = ""
username = ""
password = ""
host = ""
port = 9000
http_port = 8123
secure = 0

[nessie]
uri = ""
access-key-id = ""
secret-access-key = ""
