[project]
name = "lakehouse-oss-vs-databricks"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "dlt[s3]==1.15.0",
    "pyarrow==21.0.0",
    "pyiceberg==0.9.1",
    "python-dotenv==1.1.1",
]
