# Notebook 1 - http_to_bucket
# ===========================

[parquet_to_minio.destination.filesystem]
bucket_url = ""

[parquet_to_minio.destination.credentials]
aws_access_key_id=""
aws_secret_access_key=""
endpoint_url = ""

# Notebook 3 - Minio-to-Azure
# ===========================
[minio_to_azure.sources.filesystem.credentials]
aws_access_key_id=""
aws_secret_access_key=""
endpoint_url = ""

[minio_to_azure.destination.filesystem]
bucket_url = ""

[minio_to_azure.destination.filesystem.credentials]
azure_storage_account_name  = ""
azure_storage_account_key = ""

# Notebook 4 - Minio-to-Clickhouse
# ================================
[minio_to_clickhouse.sources.filesystem.credentials]
aws_access_key_id=""
aws_secret_access_key=""
endpoint_url = ""

[minio_to_clickhouse.destination.clickhouse.credentials]
database = ""
username = ""
password = ""
host = ""
port = 
http_port = 
secure = 
