# ===============================
# Configuración para tu destino
# ===============================
[s3_to_adls.destination.filesystem]
bucket_url = ""

[s3_to_adls.destination.filesystem.credentials]
azure_storage_account_name  = ""
azure_storage_account_key   = ""

# ===============================
# Configuración para tu origen S3/MinIO
# ===============================
[s3_to_adls.sources.filesystem]
bucket_url = ""

[s3_to_adls.sources.filesystem.credentials]
aws_access_key_id     = ""
aws_secret_access_key = ""
endpoint_url          = ""